Auth logic
DedovaA/PetProject pull request #2
Opened 2022-06-24 10:50 UTC by DedovaA

implemented AuthScreen logic

2022-06-24 11:15 UTC, Nikolaiko requested changes

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +    val authFormType = _authFormType
Если ты хочешь ограничить "урезать" возможности свойства с MutableLiveData до LiveData, то нужно явно указать тип публичного свойства :
val authFormType: LiveData<AuthFormType> = _authFormType
иначе котлин автовыведением присвоит authFormType такой же тип данных.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        clearScreenStates()
Вспомни опыт прошлых приложений, разве после неправильного ввода у тебя отчищались введенные данные? Нет. Это плохой подход. 
Плюс поведение и логика описывается в usecases проекта, там нет ничего про то, что поля должны отчищаться.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        val emailState = when {
использование when - хорошо.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +    val email = _email
1. Тоже самое с ограничением типа полей.
2. Обычно все-таки объявление полей класса делаются в одном месте сразу. В начале, а потом методы.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        _emailIsValid.postValue(state)
Тут просто подумай еще раз, есть ли необходимость выделять одну строчку в отдельную функцию.
Если решишь, что да - оставляй.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/loginScreen/AuthorizationScreen.kt
> +    val authForm = viewModel.authFormType.observeAsState(AuthFormType.login)
Хорошо. Вьюха получилась аккуратной.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/loginScreen/LoginScreen.kt
> +    LoginForm(callbackEmail, callbackPassword, email, password, emailValid, passwordValid)
Я рекомендую, если параметров больше трех :
- писать их в столбик
- указывать их имена

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/utils/UserInputValidation.kt
> +
Тут две функции : isPasswordMatch и isEmptyField - просто однострочники. Тоже, просто еще раз подумай, нужны?

Если  да, оставляй.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/viewComponents/forms/LoginForm.kt
> +            }
1. Если у тебя известное количество вариантов в when, то у последнего лучше явно писать значение варианта : 
true -> 
false ->

а не : 
true ->
else ->

2. Вот это конструкцию как раз можно вынести в отдельную функцию (тем более, что она используется у тебя ниже в другом классе):

`fun example(emailValid, email): Int {
when(emailValid){
                false -> when(email){
                    "" -> R.string.error_message_empty_field)
                    else -> R.string.error_message_email)
                }
                else -> R.string.empty_string)
            }
}
ErrorMessage(stringResource(example(emailValid, email))
`
Или как-то так.

2022-06-24 11:15 UTC, Nikolaiko commented on app/src/main/res/values/strings.xml
> +    <string name="empty_string"> </string>
Пустую строку мы делаем, но в константах обычно.
const val EMPTY_STRING = ""

2022-06-27 10:18 UTC, DedovaA commented on app/src/main/java/com/example/petproject/utils/UserInputValidation.kt
> +
согласна, что в принципе они бесполезны, я просто для наглядности их вынесла все отдельный файл

2022-06-27 10:20 UTC, DedovaA commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        _emailIsValid.postValue(state)
тут не поняла

2022-06-27 10:22 UTC, DedovaA commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        clearScreenStates()
убрала из проверок fun loginValidation() и fun registerValidation(). оставила сброс данных только при переключении экрана с "войти" на "регистрацию"

2022-06-27 10:26 UTC, DedovaA commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +    val authFormType = _authFormType
поправила

2022-06-27 10:27 UTC, DedovaA commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +    val email = _email
поправила

2022-06-27 10:28 UTC, DedovaA commented on app/src/main/java/com/example/petproject/loginScreen/LoginScreen.kt
> +    LoginForm(callbackEmail, callbackPassword, email, password, emailValid, passwordValid)
в столбик написала, что значит указывать их имена не поняла)

2022-06-27 10:29 UTC, DedovaA commented on app/src/main/java/com/example/petproject/viewComponents/forms/LoginForm.kt
> +            }
сделал отдельный файл проверками

2022-06-27 10:29 UTC, DedovaA commented on app/src/main/res/values/strings.xml
> +    <string name="empty_string"> </string>
не знаю, куда вынести эту константу, сделала для нее отдельный файл

2022-06-27 14:37 UTC, Nikolaiko commented on app/src/main/java/com/example/petproject/AuthViewModel.kt
> +        _emailIsValid.postValue(state)
Это я не до конца понял код сначала, все ок.

2022-06-27 14:43 UTC, merged